# -*- coding: utf-8 -*-
"""count the number of digits in the integer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGcX6QtMAQf5_KsSoHm9L3ZHdzCOoTM7
"""

def count_digits(n):
    if n < 10 and n >= 0:
        return 1
    else:
        return 1 + count_digits(n // 10)

print(count_digits(12345))