# -*- coding: utf-8 -*-
"""count the digits in string

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGcX6QtMAQf5_KsSoHm9L3ZHdzCOoTM7
"""

def count_digits_in_string(s):
    if s == "":
        return 0
    elif s[0].isdigit():
        return 1 + count_digits_in_string(s[1:])
    else:
        return count_digits_in_string(s[1:])

print(count_digits_in_string("abc123def456"))