# -*- coding: utf-8 -*-
"""decimal to binary using recursion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CTI9J9iLd3FMCEixnb1Dxwkmw7Ymzxaz
"""

def decimal_to_binary(n):
    if n == 0:
        return "0"
    elif n == 1:
        return "1"
    return decimal_to_binary(n // 2) + str(n % 2)

n = float(input("Enter a decimal number: "))
print("Binary equivalent:", decimal_to_binary(n))