# -*- coding: utf-8 -*-
"""fibonacci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AgxBzTqfAT99rvw-4FkgCqyNkNartVsc
"""

def odd_fib(n):
    if n == 0:
        return 1
    return even_fib(n - 1) + odd_fib(n - 1)

def fibonacci(n):
    if n % 2 == 0:
        return even_fib(n // 2)
    else:
        return odd_fib(n // 2)

# Example usage:
n = int(input("Enter the number of terms: "))
print("Fibonacci series:", [fibonacci(i) for i in range(n)])