# -*- coding: utf-8 -*-
"""length of string using recursion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGcX6QtMAQf5_KsSoHm9L3ZHdzCOoTM7
"""

def string_length(s):
    if s == "":
        return 0
    else:
        return 1 + string_length(s[1:])

print(string_length("Hello"))