# -*- coding: utf-8 -*-
"""reverse string

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGcX6QtMAQf5_KsSoHm9L3ZHdzCOoTM7
"""

def print_reverse(s):
    if s == "":
        return
    else:
        print(s[-1], end="")
        print_reverse(s[:-1])
print_reverse("Hello")