# -*- coding: utf-8 -*-
"""sum of first n natural numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGcX6QtMAQf5_KsSoHm9L3ZHdzCOoTM7
"""

def sum_natural_numbers(n):
    if n == 1:
        return 1
    else:
        return n + sum_natural_numbers(n - 1)

print(sum_natural_numbers(5))