# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xAXg7MEzjbBW2etYeLFpnUlXXT9xJOst
"""

def tower_of_hanoi(n, source, auxiliary, target):
    if n == 1:
        print(f"Move disk 1 from {source} to {target}")
        return

    # Move n-1 disks from source to auxiliary peg
    tower_of_hanoi(n - 1, source, target, auxiliary)

    # Move the nth disk from source to target peg
    print(f"Move disk {n} from {source} to {target}")

    # Move n-1 disks from auxiliary to target peg
    tower_of_hanoi(n - 1, auxiliary, source, target)

# Example usage:
n = int(input("Enter the number of disks: "))
tower_of_hanoi(n, 'A', 'B', 'C')